version: "3"

services:
  amb:
    image: ldviet92/huongnghieptre-frontend:latest
    environment:
      - NODE_ENV=PROD
    ports:
      - 3000:3000
    networks:
      - root_app-tier
networks:
  root_app-tier:
    external: true
